### ISSUE TITLE
Spring Actuator like "Admin Processes" features

### ISSUE THREAD

**Issue by krmeda** [philips-software/logproxy#5]
Authenticated endpoints for
- [x] Health Monitoring: System Health HTTP Endpoint (includes health of RMQ or dependency services)
- [x] Metrics: Prometheus style (probably have to look at a Datadog Agent/New Relic agent support later)

**Comment by loafoe** [comment]
`v1.7.3` introduces a Prometheus compatible metrics endpoint giving insights into the internals. There are 3 custom metrics introduced:

* `logproxy_enhanced_transaction_ids_total` -- counts number of transactionIds generated on incomplete LogEvents
* `logproxy_enhanced_encoded_messages_total` -- counts the number of times unencoded `message` fields were found and fixed
* `logproxy_processed_total`-- total number of log messages processed since the start of the process

Future versions will include additional metrics
